-- MySQL Script generated by MySQL Workbench
-- 11/27/14 23:29:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gescrum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gescrum` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `gescrum` ;

-- -----------------------------------------------------
-- Table `gescrum`.`tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_usuario` (
  `usu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_apellido_paterno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_apellido_materno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `usu_correo` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_clave` INT(11) NOT NULL,
  `usu_estado` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_login_conexion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_fecha_inicio` DATE NOT NULL,
  `usu_fecha_modificacion` DATE NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_proyecto` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_proyecto` (
  `pro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_estado` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_fecha_creacion` DATE NOT NULL,
  `tbl_usuario_usu_id` INT(11) NOT NULL,
  PRIMARY KEY (`pro_id`),
  CONSTRAINT `fk_tbl_proyecto_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_id`)
    REFERENCES `gescrum`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_proyecto_tbl_usuario1_idx` ON `gescrum`.`tbl_proyecto` (`tbl_usuario_usu_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_hdu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_hdu` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_hdu` (
  `hdu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `hdu_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_prioridad` INT(11) NULL DEFAULT NULL,
  `hdu_eventum` INT(11) NULL DEFAULT NULL,
  `hdu_descripcion` VARCHAR(5000) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_dependencia` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `hdu_criterios_aceptacion` VARCHAR(1500) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_proyecto_pro_id` INT(11) NOT NULL,
  PRIMARY KEY (`hdu_id`),
  CONSTRAINT `fk_tbl_hdu_tbl_proyecto1`
    FOREIGN KEY (`tbl_proyecto_pro_id`)
    REFERENCES `gescrum`.`tbl_proyecto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_hdu_tbl_proyecto1_idx` ON `gescrum`.`tbl_hdu` (`tbl_proyecto_pro_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_tarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_tarea` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_tarea` (
  `tar_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tar_descripcion` VARCHAR(1000) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tar_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tar_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_hdu_hdu_id` INT(11) NOT NULL,
  PRIMARY KEY (`tar_id`),
  CONSTRAINT `fk_tbl_tarea_tbl_hdu1`
    FOREIGN KEY (`tbl_hdu_hdu_id`)
    REFERENCES `gescrum`.`tbl_hdu` (`hdu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_tarea_tbl_hdu1_idx` ON `gescrum`.`tbl_tarea` (`tbl_hdu_hdu_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_estado` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_estado` (
  `est_id` INT(11) NOT NULL AUTO_INCREMENT,
  `est_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_descripcion` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_tarea_tar_id` INT(11) NOT NULL,
  PRIMARY KEY (`est_id`),
  CONSTRAINT `fk_tbl_estado_tbl_tarea1`
    FOREIGN KEY (`tbl_tarea_tar_id`)
    REFERENCES `gescrum`.`tbl_tarea` (`tar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_estado_tbl_tarea1_idx` ON `gescrum`.`tbl_estado` (`tbl_tarea_tar_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_grupo` ;
CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_grupo` 
(
    `gru_id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `gru_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
    `gru_descripcion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
    `gru_estado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
    `gru_usu_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
    `gru_fecha_creacion` DATETIME NOT NULL,
    `gru_fecha_modificacion` DATETIME NOT NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;




-- -----------------------------------------------------
-- Table `gescrum`.`tbl_sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_sprint` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_sprint` (
  `spr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `spr_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `spr_descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `spr_fecha_creacion` DATE NOT NULL,
  `spr_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_grupo_gru_id` INT(11) NOT NULL,
  PRIMARY KEY (`spr_id`),
  CONSTRAINT `fk_tbl_sprint_tbl_grupo1`
    FOREIGN KEY (`tbl_grupo_gru_id`)
    REFERENCES `gescrum`.`tbl_grupo` (`gru_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_sprint_tbl_grupo1_idx` ON `gescrum`.`tbl_sprint` (`tbl_grupo_gru_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_hdu_x_sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_hdu_x_sprint` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_hdu_x_sprint` (
  `tbl_sprint_spr_id` INT(11) NOT NULL,
  `ts_esfuerzo` INT(11) NOT NULL,
  `ts_usuario_asignado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ts_estado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ts_fecha_mod` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_tarea_tar_id` INT(11) NOT NULL,
  PRIMARY KEY (`tbl_sprint_spr_id`, `tbl_tarea_tar_id`),
  CONSTRAINT `fk_tbl_hdu_has_tbl_sprint_tbl_sprint1`
    FOREIGN KEY (`tbl_sprint_spr_id`)
    REFERENCES `gescrum`.`tbl_sprint` (`spr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_hdu_has_tbl_sprint_tbl_tarea1`
    FOREIGN KEY (`tbl_tarea_tar_id`)
    REFERENCES `gescrum`.`tbl_tarea` (`tar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_hdu_has_tbl_sprint_tbl_sprint1_idx` ON `gescrum`.`tbl_hdu_x_sprint` (`tbl_sprint_spr_id` ASC);

CREATE INDEX `fk_tbl_hdu_has_tbl_sprint_tbl_tarea1_idx` ON `gescrum`.`tbl_hdu_x_sprint` (`tbl_tarea_tar_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_repositorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_repositorio` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_repositorio` (
  `rep_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rep_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rep_descripcion` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rep_fecha_creacion` DATE NOT NULL,
  `tbl_hdu_hdu_id` INT(11) NOT NULL,
  PRIMARY KEY (`rep_id`),
  CONSTRAINT `fk_tbl_repositorio_tbl_hdu1`
    FOREIGN KEY (`tbl_hdu_hdu_id`)
    REFERENCES `gescrum`.`tbl_hdu` (`hdu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_repositorio_tbl_hdu1_idx` ON `gescrum`.`tbl_repositorio` (`tbl_hdu_hdu_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_rol` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_rol` (
  `rol_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_descripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rol_estado` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rol_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_rol_x_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_rol_x_usuario` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_rol_x_usuario` (
  `tbl_rol_rol_id` INT(11) NOT NULL,
  `tbl_usuario_usu_id` INT(11) NOT NULL,
  `ro_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `ro_estado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `ro_fecha_creacion` DATE NULL DEFAULT NULL,
  `ro_usuario_modificacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `ro_fecha_mod` DATE NULL DEFAULT NULL,
  CONSTRAINT `fk_tbl_rol_has_tbl_usuario_tbl_rol`
    FOREIGN KEY (`tbl_rol_rol_id`)
    REFERENCES `gescrum`.`tbl_rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_rol_has_tbl_usuario_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_id`)
    REFERENCES `gescrum`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_rol_has_tbl_usuario_tbl_usuario1_idx` ON `gescrum`.`tbl_rol_x_usuario` (`tbl_usuario_usu_id` ASC);

CREATE INDEX `fk_tbl_rol_has_tbl_usuario_tbl_rol_idx` ON `gescrum`.`tbl_rol_x_usuario` (`tbl_rol_rol_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_test_case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_test_case` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_test_case` (
  `test_id` INT(11) NOT NULL,
  `test_enunciado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_objetivo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_dato_requerido` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_precondiciones` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `test_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_tarea_tar_id` INT(11) NOT NULL,
  PRIMARY KEY (`test_id`),
  CONSTRAINT `fk_tbl_test_case_tbl_tarea1`
    FOREIGN KEY (`tbl_tarea_tar_id`)
    REFERENCES `gescrum`.`tbl_tarea` (`tar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_test_case_tbl_tarea1_idx` ON `gescrum`.`tbl_test_case` (`tbl_tarea_tar_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_usuario_grupo`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `gescrum`.`tbl_usuario_grupo` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_usuario_grupo` (
  `tbl_usuario_usu_id` INT(11) NOT NULL,
  `tbl_grupo_gru_id` INT(11) NOT NULL,
  `ug_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ug_fecha_creacion` DATE NOT NULL,
  `ug_usuario_modificacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ug_fecha_mod` DATE NOT NULL,
  PRIMARY KEY (`tbl_usuario_usu_id`, `tbl_grupo_gru_id`),
  CONSTRAINT `fk_table1_tbl_grupo1`
    FOREIGN KEY (`tbl_grupo_gru_id`)
    REFERENCES `gescrum`.`tbl_grupo` (`gru_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_id`)
    REFERENCES `gescrum`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_table1_tbl_grupo1_idx` ON `gescrum`.`tbl_usuario_grupo` (`tbl_grupo_gru_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


alter table gescrum.tbl_usuario add 
(usu_creado_por varchar(30) not null ); 
alter table gescrum.tbl_usuario add 
(usu_modificado_por varchar(30) not null );






ALTER TABLE tbl_rol AUTO_INCREMENT=1;
INSERT INTO `gescrum`.`tbl_rol`(`rol_descripcion`,`rol_estado`,`rol_fecha_creacion`)VALUES('Analista QA','vigente',now());
INSERT INTO `gescrum`.`tbl_rol`(`rol_descripcion`,`rol_estado`,`rol_fecha_creacion`)VALUES('Desarrolador','vigente',now());
INSERT INTO `gescrum`.`tbl_rol`(`rol_descripcion`,`rol_estado`,`rol_fecha_creacion`)VALUES('Scrum Master','vigente',now());
INSERT INTO `gescrum`.`tbl_rol`(`rol_descripcion`,`rol_estado`,`rol_fecha_creacion`)VALUES('Product Owner','vigente',now());
INSERT INTO `gescrum`.`tbl_rol`(`rol_descripcion`,`rol_estado`,`rol_fecha_creacion`)VALUES('provisorio','vigente',now());

ALTER TABLE tbl_usuario AUTO_INCREMENT=1;
INSERT INTO `gescrum`.`tbl_usuario`(`usu_nombre`,`usu_apellido_paterno`,`usu_apellido_materno`,`usu_correo`,`usu_clave`,`usu_estado`,`usu_login_conexion`,`usu_fecha_inicio`,`usu_fecha_modificacion`,`usu_creado_por`,`usu_modificado_por`)VALUES('Daniel','Valdebenito','González','tanganiel@hotmail.com','123456','vigente','tanganiel',now(),now(),'tanganiel','tanganiel');
INSERT INTO `gescrum`.`tbl_usuario`(`usu_nombre`,`usu_apellido_paterno`,`usu_apellido_materno`,`usu_correo`,`usu_clave`,`usu_estado`,`usu_login_conexion`,`usu_fecha_inicio`,`usu_fecha_modificacion`,`usu_creado_por`,`usu_modificado_por`)VALUES('Jordan','Carrasco','Donoso','jecarrasco@gmail.com','123456','vigente','jecarrasco',now(),now(),'tanganiel','tanganiel');
INSERT INTO `gescrum`.`tbl_usuario`(`usu_nombre`,`usu_apellido_paterno`,`usu_apellido_materno`,`usu_correo`,`usu_clave`,`usu_estado`,`usu_login_conexion`,`usu_fecha_inicio`,`usu_fecha_modificacion`,`usu_creado_por`,`usu_modificado_por`)VALUES('Emilio','Landskron','Cid','kaede.keisuke@hotmail.com','123456','vigente','emilio',now(),now(),'tanganiel','tanganiel');
INSERT INTO `gescrum`.`tbl_usuario`(`usu_nombre`,`usu_apellido_paterno`,`usu_apellido_materno`,`usu_correo`,`usu_clave`,`usu_estado`,`usu_login_conexion`,`usu_fecha_inicio`,`usu_fecha_modificacion`,`usu_creado_por`,`usu_modificado_por`)VALUES('Nicolás','Fuenzalida','Zuniga','ripcrow@hotmail.com','123456','vigente','ripcrow',now(),now(),'tanganiel','tanganiel');


INSERT INTO `gescrum`.`tbl_rol_x_usuario`(`tbl_rol_rol_id`,`tbl_usuario_usu_id`,`ro_usuario_creador`,`ro_estado`,`ro_fecha_creacion`,`ro_usuario_modificacion`,`ro_fecha_mod`)VALUES(3,1,'tanganiel','vigente','now()','tanganiel',now());
INSERT INTO `gescrum`.`tbl_rol_x_usuario`(`tbl_rol_rol_id`,`tbl_usuario_usu_id`,`ro_usuario_creador`,`ro_estado`,`ro_fecha_creacion`,`ro_usuario_modificacion`,`ro_fecha_mod`)VALUES(3,2,'tanganiel','vigente','now()','tanganiel',now());
INSERT INTO `gescrum`.`tbl_rol_x_usuario`(`tbl_rol_rol_id`,`tbl_usuario_usu_id`,`ro_usuario_creador`,`ro_estado`,`ro_fecha_creacion`,`ro_usuario_modificacion`,`ro_fecha_mod`)VALUES(3,3,'tanganiel','vigente','now()','tanganiel',now());
INSERT INTO `gescrum`.`tbl_rol_x_usuario`(`tbl_rol_rol_id`,`tbl_usuario_usu_id`,`ro_usuario_creador`,`ro_estado`,`ro_fecha_creacion`,`ro_usuario_modificacion`,`ro_fecha_mod`)VALUES(3,4,'tanganiel','vigente','now()','tanganiel',now());



ALTER TABLE tbl_proyecto AUTO_INCREMENT=1;
INSERT INTO `gescrum`.`tbl_proyecto`(`pro_nombre`,`pro_descripcion`,`pro_estado`,`pro_fecha_creacion`,`tbl_usuario_usu_id`)VALUES('Gescrum 1','Prueba en la base de datos','vigente',now(),1);

ALTER TABLE tbl_hdu AUTO_INCREMENT=1;
INSERT INTO `gescrum`.`tbl_hdu`(`hdu_nombre`,`hdu_prioridad`,`hdu_eventum`,`hdu_descripcion`,`hdu_dependencia`,`hdu_criterios_aceptacion`,`hdu_fecha_creacion`,`hdu_usuario_creador`,`tbl_proyecto_pro_id`)VALUES('historia 1',10,450,'Esta es una prueba de base de datos para historias de usuario','sistemas','inicial',now(),'tanganiel',1);

ALTER TABLE tbl_grupo AUTO_INCREMENT=1;
insert into tbl_grupo (gru_nombre, gru_descripcion,gru_estado,gru_usu_creador,gru_fecha_creacion,gru_fecha_modificacion)
values ('grupo 1','Grupo de prueba','vigente','tanganiel',now(), now());
insert into tbl_grupo (gru_nombre, gru_descripcion,gru_estado,gru_usu_creador,gru_fecha_creacion,gru_fecha_modificacion)
values ('grupo 2','Grupo de prueba','vigente','tanganiel',now(), now());



ALTER TABLE tbl_sprint AUTO_INCREMENT=1;
insert into tbl_sprint (spr_nombre, spr_descripcion, spr_fecha_creacion,spr_usuario_creador,tbl_grupo_gru_id) 
values ('spring 1','spring de prueba',now(),'tanganiel',1);


ALTER TABLE `gescrum`.`tbl_hdu_x_sprint` 
DROP PRIMARY KEY;


-- ingreso de tareas --
ALTER TABLE tbl_tarea AUTO_INCREMENT=1;
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 1 de prueba','2014-11-28','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 2 de prueba','2014-11-28','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 3 de prueba','2014-12-01','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 4 de prueba','2014-12-01','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 5 de prueba','2014-12-02','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 6 de prueba','2014-12-02','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 7 de prueba','2014-12-03','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 8 de prueba','2014-12-03','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 9 de prueba','2014-12-04','tanganiel',1);
insert into tbl_tarea (tar_descripcion, tar_fecha_creacion, tar_usuario_creador,tbl_hdu_hdu_id) 
values ('Tarea 10 de prueba','2014-12-04','tanganiel',1);

-- Iteraciones --
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,300,'tanganiel','vigente',(select tar_fecha_creacion from tbl_tarea where tar_id = 1),1);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,300,'tanganiel','vigente',(select tar_fecha_creacion from tbl_tarea where tar_id = 2),2);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,300,'tanganiel','vigente',(select tar_fecha_creacion from tbl_tarea where tar_id = 3),3);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,300,'tanganiel','vigente',(select tar_fecha_creacion from tbl_tarea where tar_id = 4),4);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,300,'tanganiel','vigente',(select tar_fecha_creacion from tbl_tarea where tar_id = 5),5);

INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,0,'tanganiel','vigente','2014-12-01',1);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,0,'tanganiel','vigente','2014-12-01',2);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,0,'tanganiel','vigente','2014-12-01',3);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,0,'tanganiel','vigente','2014-12-01',4);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,0,'tanganiel','vigente','2014-12-01',5);

INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,250,'tanganiel','vigente','2014-12-02',1);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,200,'tanganiel','vigente','2014-12-02',2);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,230,'tanganiel','vigente','2014-12-02',3);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,100,'tanganiel','vigente','2014-12-02',4);
INSERT INTO `gescrum`.`tbl_hdu_x_sprint`(`tbl_sprint_spr_id`,`ts_esfuerzo`,`ts_usuario_asignado`,`ts_estado`,`ts_fecha_mod`,`tbl_tarea_tar_id`)
VALUES(1,1500,'tanganiel','vigente','2014-12-02',5);





  

/*
-- Consulta de esfuerzo --
select hs.ts_fecha_crea 'fechaC', sum(hs.ts_esfuerzo) 'iteracion' 
from tbl_hdu_x_sprint hs
where hs.ts_iteracion = 1 -- iteración
and hs.tbl_sprint_spr_id = 1 -- id del sprint
and ts_fecha_crea between (select min(ts_fecha_crea) from tbl_hdu_x_sprint where tbl_sprint_spr_id = hs.tbl_sprint_spr_id ) and (select max(ts_fecha_crea) from tbl_hdu_x_sprint where tbl_sprint_spr_id = hs.tbl_sprint_spr_id)
group by hs.ts_fecha_crea;
*/