-- MySQL Script generated by MySQL Workbench
-- 11/23/14 20:35:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gescrum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gescrum` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `gescrum` ;

-- -----------------------------------------------------
-- Table `gescrum`.`tbl_aplicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_aplicacion` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_aplicacion` (
  `app_id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `app_fecha_creacion` DATE NOT NULL,
  `app_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`app_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_usuario` (
  `usu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_apellido_paterno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_apellido_materno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `usu_correo` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_clave` INT(11) NOT NULL,
  `usu_estado` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_login_conexion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `usu_fecha_inicio` DATE NOT NULL,
  `usu_fecha_modificacion` DATE NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_proyecto` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_proyecto` (
  `pro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_estado` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pro_fecha_creacion` DATE NOT NULL,
  `tbl_usuario_usu_id` INT(11) NOT NULL,
  PRIMARY KEY (`pro_id`),
  CONSTRAINT `fk_tbl_proyecto_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_id`)
    REFERENCES `gescrum`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_proyecto_tbl_usuario1_idx` ON `gescrum`.`tbl_proyecto` (`tbl_usuario_usu_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_hdu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_hdu` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_hdu` (
  `hdu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `hdu_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_prioridad` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_eventum` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `hdu_descripcion` VARCHAR(5000) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_dependencia` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `hdu_criterios_aceptacion` VARCHAR(1500) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_aplicacion_app_id` INT(11) NOT NULL,
  `tbl_backlog_blog_id` INT(11) NOT NULL,
  `tbl_proyecto_pro_id` INT(11) NOT NULL,
  PRIMARY KEY (`hdu_id`),
  CONSTRAINT `fk_tbl_hdu_tbl_aplicacion1`
    FOREIGN KEY (`tbl_aplicacion_app_id`)
    REFERENCES `gescrum`.`tbl_aplicacion` (`app_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_hdu_tbl_proyecto1`
    FOREIGN KEY (`tbl_proyecto_pro_id`)
    REFERENCES `gescrum`.`tbl_proyecto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_hdu_tbl_aplicacion1_idx` ON `gescrum`.`tbl_hdu` (`tbl_aplicacion_app_id` ASC);

CREATE INDEX `fk_tbl_hdu_tbl_proyecto1_idx` ON `gescrum`.`tbl_hdu` (`tbl_proyecto_pro_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_tarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_tarea` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_tarea` (
  `tar_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tar_descripcion` VARCHAR(1000) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tar_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tar_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_hdu_hdu_id` INT(11) NOT NULL,
  PRIMARY KEY (`tar_id`),
  CONSTRAINT `fk_tbl_tarea_tbl_hdu1`
    FOREIGN KEY (`tbl_hdu_hdu_id`)
    REFERENCES `gescrum`.`tbl_hdu` (`hdu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_tarea_tbl_hdu1_idx` ON `gescrum`.`tbl_tarea` (`tbl_hdu_hdu_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_estado` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_estado` (
  `est_id` INT(11) NOT NULL AUTO_INCREMENT,
  `est_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_descripcion` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_tarea_tar_id` INT(11) NOT NULL,
  PRIMARY KEY (`est_id`),
  CONSTRAINT `fk_tbl_estado_tbl_tarea1`
    FOREIGN KEY (`tbl_tarea_tar_id`)
    REFERENCES `gescrum`.`tbl_tarea` (`tar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_estado_tbl_tarea1_idx` ON `gescrum`.`tbl_estado` (`tbl_tarea_tar_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_grupo` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_grupo` (
  `gru_id` INT(11) NOT NULL,
  `gru_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `gru_descripcion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`gru_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_sprint` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_sprint` (
  `spr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `spr_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `spr_descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `spr_fecha_creacion` DATE NOT NULL,
  `spr_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_grupo_gru_id` INT(11) NOT NULL,
  PRIMARY KEY (`spr_id`),
  CONSTRAINT `fk_tbl_sprint_tbl_grupo1`
    FOREIGN KEY (`tbl_grupo_gru_id`)
    REFERENCES `gescrum`.`tbl_grupo` (`gru_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_sprint_tbl_grupo1_idx` ON `gescrum`.`tbl_sprint` (`tbl_grupo_gru_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_hdu_x_sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_hdu_x_sprint` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_hdu_x_sprint` (
  `tbl_sprint_spr_id` INT(11) NOT NULL,
  `hdu_spr_esfuerzo` INT(11) NOT NULL,
  `hdu_spr_usuario` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_spr_estado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hdu_spr_fecha_mod` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_tarea_tar_id` INT(11) NOT NULL,
  PRIMARY KEY (`tbl_sprint_spr_id`, `tbl_tarea_tar_id`),
  CONSTRAINT `fk_tbl_hdu_has_tbl_sprint_tbl_sprint1`
    FOREIGN KEY (`tbl_sprint_spr_id`)
    REFERENCES `gescrum`.`tbl_sprint` (`spr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_hdu_has_tbl_sprint_tbl_tarea1`
    FOREIGN KEY (`tbl_tarea_tar_id`)
    REFERENCES `gescrum`.`tbl_tarea` (`tar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_hdu_has_tbl_sprint_tbl_sprint1_idx` ON `gescrum`.`tbl_hdu_x_sprint` (`tbl_sprint_spr_id` ASC);

CREATE INDEX `fk_tbl_hdu_has_tbl_sprint_tbl_tarea1_idx` ON `gescrum`.`tbl_hdu_x_sprint` (`tbl_tarea_tar_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_repositorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_repositorio` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_repositorio` (
  `rep_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rep_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rep_descripcion` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rep_fecha_creacion` DATE NOT NULL,
  `tbl_hdu_hdu_id` INT(11) NOT NULL,
  PRIMARY KEY (`rep_id`),
  CONSTRAINT `fk_tbl_repositorio_tbl_hdu1`
    FOREIGN KEY (`tbl_hdu_hdu_id`)
    REFERENCES `gescrum`.`tbl_hdu` (`hdu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_repositorio_tbl_hdu1_idx` ON `gescrum`.`tbl_repositorio` (`tbl_hdu_hdu_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_rol` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_rol` (
  `rol_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_descripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rol_estado` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `rol_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_rol_x_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_rol_x_usuario` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_rol_x_usuario` (
  `tbl_rol_rol_id` INT(11) NOT NULL,
  `tbl_usuario_usu_id` INT(11) NOT NULL,
  `ro_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `ro_estado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `ro_fecha_creacion` DATE NULL,
  `ro_usuario_modificacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `ro_fecha_mod` DATE NULL,
  PRIMARY KEY (`tbl_rol_rol_id`, `tbl_usuario_usu_id`),
  CONSTRAINT `fk_tbl_rol_has_tbl_usuario_tbl_rol`
    FOREIGN KEY (`tbl_rol_rol_id`)
    REFERENCES `gescrum`.`tbl_rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_rol_has_tbl_usuario_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_id`)
    REFERENCES `gescrum`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_rol_has_tbl_usuario_tbl_usuario1_idx` ON `gescrum`.`tbl_rol_x_usuario` (`tbl_usuario_usu_id` ASC);

CREATE INDEX `fk_tbl_rol_has_tbl_usuario_tbl_rol_idx` ON `gescrum`.`tbl_rol_x_usuario` (`tbl_rol_rol_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_test_case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_test_case` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_test_case` (
  `test_id` INT(11) NOT NULL,
  `test_enunciado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_objetivo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_dato_requerido` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_precondiciones` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `test_fecha_creacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `test_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tbl_tarea_tar_id` INT(11) NOT NULL,
  PRIMARY KEY (`test_id`),
  CONSTRAINT `fk_tbl_test_case_tbl_tarea1`
    FOREIGN KEY (`tbl_tarea_tar_id`)
    REFERENCES `gescrum`.`tbl_tarea` (`tar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_tbl_test_case_tbl_tarea1_idx` ON `gescrum`.`tbl_test_case` (`tbl_tarea_tar_id` ASC);


-- -----------------------------------------------------
-- Table `gescrum`.`tbl_usuario_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gescrum`.`tbl_usuario_grupo` ;

CREATE TABLE IF NOT EXISTS `gescrum`.`tbl_usuario_grupo` (
  `tbl_usuario_usu_id` INT(11) NOT NULL,
  `tbl_grupo_gru_id` INT(11) NOT NULL,
  `ug_usuario_creador` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `ug_estado` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `ug_fecha_creacion` DATE NULL,
  `ug_usuario_modificacion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL,
  `ug_fecha_mod` DATE NULL,
  PRIMARY KEY (`tbl_usuario_usu_id`, `tbl_grupo_gru_id`),
  CONSTRAINT `fk_table1_tbl_grupo1`
    FOREIGN KEY (`tbl_grupo_gru_id`)
    REFERENCES `gescrum`.`tbl_grupo` (`gru_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_id`)
    REFERENCES `gescrum`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

CREATE INDEX `fk_table1_tbl_grupo1_idx` ON `gescrum`.`tbl_usuario_grupo` (`tbl_grupo_gru_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
